workspace:
  base: /go
  path: src/git.esheavyindustries.com/esell/blockhead

pipeline:
  test:
    image: golang:1.9.2
    commands:
      - apt-get -y install curl
      - go test -cover -coverprofile coverage.out
      - curl -XPOST 'http://esheavyindustries.com:8080/upload?repo=blockhead_git' -F "file=@coverage.out"

  build:
    image: golang:1.9.2
    commands:
      - apt-get -y install curl
      - GOOS=linux GOARCH=amd64 go build -o blockhead_linux
      - GOOS=darwin GOARCH=amd64 go build -o blockhead_darwin
      - GOOS=windows GOARCH=amd64 go build -o blockhead_windows.exe
